import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#f0f2f5",
    marginTop: 20,
  },
  backButton: {
    padding: 10,
    marginTop: 20,
    marginLeft: 15,
  },
  card: {
    backgroundColor: "white",
    borderRadius: 10,
    marginHorizontal: 15,
    padding: 15,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
    marginBottom: 15,
  },
  profileHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  profileImage: {
    width: 90,
    height: 90,
    borderRadius: 45,
    borderWidth: 3,
    borderColor: "#fff",
  },
  profileInfo: {
    marginLeft: 15,
    justifyContent: "center",
    flex: 1,
  },
  name: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#3d3d3d",
    marginBottom: 5,
  },
  profileDetails: {
    fontSize: 14,
    color: "#65676b",
    marginBottom: 5,
  },
  editButton: {
    flexDirection: "row",
    backgroundColor: "#1877f2",
    paddingVertical: 8,
    paddingHorizontal: 15,
    borderRadius: 5,
    alignItems: "center",
    marginTop: 10,
    width: 160,
    justifyContent: "center",
  },
  editText: {
    color: "white",
    marginLeft: 5,
    fontSize: 14,
  },
  profilePosts: {
    marginHorizontal: 15,
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#3d3d3d",
    marginBottom: 10,
  },
  post: {
    backgroundColor: "#fff",
    borderRadius: 8,
    padding: 12,
    borderColor: "#ddd",
    borderWidth: 1,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 4,
    marginBottom: 10,
  },
  postImage: {
    width: "100%",
    height: 150,
    borderRadius: 8,
    marginBottom: 10,
    resizeMode: "cover",
  },
  postDetails: {
    marginBottom: 10,
  },
  postTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#333",
  },
  postPrice: {
    fontSize: 14,
    color: "#1c1e21",
    fontWeight: "500",
  },
  soldButton: {
    backgroundColor: "#1877f2",
    paddingVertical: 8,
    borderRadius: 5,
    alignItems: "center",
  },
  soldButtonText: {
    color: "white",
    fontSize: 14,
  },
  viewAllButton: {
    backgroundColor: "#ddd",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 5,
    alignItems: "center",
    marginTop: 10,
  },
  viewAllText: {
    fontSize: 14,
    color: "#1877f2",
    fontWeight: "bold",
  },
});
