import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  modalContainer: {
    backgroundColor: "white",
    padding: 20,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    height: "90%",
    width: "100%",
  },
  countryModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "flex-end",
  },
  countryModalContainer: {
    backgroundColor: "white",
    padding: 20,
    borderTopLeftRadius: 15,
    borderTopRightRadius: 15,
    height: "70%",
    width: "100%",
    position: "absolute",
    bottom: 0,
  },
  closeButton: {
    alignSelf: "flex-end",
    padding: 10,
    position: "absolute",
    right: 20,
    top: 20,
    zIndex: 1,
  },
  closeText: {
    fontSize: 24,
    fontWeight: "bold",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 20,
    textAlign: "center",
    marginTop: 40,
  },
  countryItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: "#ddd",
  },
  countryInfo: {
    flex: 1,
  },
  countryText: {
    fontSize: 16,
    color: "#3d3d3d",
    fontFamily: "Onest-Regular",
    fontWeight: 500,
  },
  checkbox: {
    marginLeft: 10,
    borderWidth: 2,
    height: 30,
    width: 30,
    fontSize: 30,
    borderRadius: 4,
    borderColor: "#ff9696",
  },
  inputContainer: {
    width: "100%",
    marginBottom: 20,
  },
  selectContainer: {
    marginBottom: 10,
  },
  placeholder: {
    fontSize: 16,
    color: "#777",
    marginBottom: 5,
  },
  pickerButton: {
    padding: 10,
    backgroundColor: "#f0f0f0",
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#ddd",
  },
  input: {
    padding: 10,
    backgroundColor: "#f0f0f0",
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#ddd",
    marginBottom: 10,
  },
  message: {
    marginBottom: 20,
    fontSize: 14,
    color: "#555",
  },
  continueButton: {
    backgroundColor: "#ff0000",
    padding: 15,
    borderRadius: 5,
    marginBottom: 40,
    width: "100%",
    alignItems: "center",
  },
  continueButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  separator: {
    marginBottom: 40,
    alignItems: "center",
  },
  socialButton: {
    backgroundColor: "#fff",
    padding: 12,
    borderRadius: 5,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#3d3d3d",
    width: "100%",
    alignItems: "center",
  },
  errorsInputs: {
    color: "#ff0000",
    fontWeight: "semibold",
  },

  container: {
    flexDirection: "column",
    justifyContent: "center",
    marginTop: 20,
    marginBottom: 30,
  },
  contentCode: {
    flexDirection: "row",
  },
  textCode: {
    marginBottom: 20,
    textAlign: "center",
    color: "#3d3d3d",
  },
  inputCode: {
    width: 50,
    height: 60,
    borderWidth: 2,
    textAlign: "center",
    fontSize: 22,
    marginHorizontal: 8,
    borderRadius: 10,
    backgroundColor: "#fff",
    elevation: 5, // Sombra en Android
    shadowColor: "#000", // Sombra en iOS
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
});
